# -*- coding: utf-8 -*-
"""Preserve an input EPUB's chapter hierarchy across KCC image processing.

KCC extracts comic EPUB pages in spine order, then renames the extracted images
as ``kcc-0001`` ... before image processing.  This module captures the original
EPUB3 NAV (or EPUB2 NCX fallback) while the source package is still available,
and later remaps each navigation target to the processed XHTML page generated by
KCC.  The default KCC TOC remains in place whenever capture/remapping cannot be
proved safe.
"""
from __future__ import annotations

from copy import deepcopy
import os
from pathlib import Path
import posixpath
import re
import tempfile
import xml.etree.ElementTree as ET
from urllib.parse import unquote, urlsplit

XHTML_NS = "http://www.w3.org/1999/xhtml"
EPUB_NS = "http://www.idpf.org/2007/ops"
NCX_NS = "http://www.daisy.org/z3986/2005/ncx/"
XML_NS = "http://www.w3.org/XML/1998/namespace"
SCHEMA = "kcc-kindle-cn.epub-toc.v1"
_PAGE_RE = re.compile(r"(?:^|[^0-9A-Za-z])kcc-(\d{4})(?:[^0-9]|$)", re.IGNORECASE)


def _local(tag: str) -> str:
    return tag.rsplit("}", 1)[-1] if "}" in tag else tag


def _direct_children(element: ET.Element, name: str) -> list[ET.Element]:
    return [child for child in list(element) if _local(child.tag) == name]


def _first_direct(element: ET.Element, name: str) -> ET.Element | None:
    for child in list(element):
        if _local(child.tag) == name:
            return child
    return None


def _text(element: ET.Element | None) -> str:
    if element is None:
        return ""
    return " ".join("".join(element.itertext()).split())


def _safe_target(base_dir: str, href: str | None) -> str | None:
    """Normalize one EPUB-internal reference to a root-relative POSIX path."""
    raw = unquote(str(href or "").strip())
    if not raw:
        return None
    parsed = urlsplit(raw)
    if parsed.scheme or parsed.netloc:
        return None
    path = parsed.path.replace("\\", "/")
    if not path or path.startswith("/"):
        return None
    normalized = posixpath.normpath(posixpath.join(base_dir, path))
    if normalized in ("", ".") or normalized == ".." or normalized.startswith("../"):
        return None
    return normalized.lstrip("./")


def _root_relative(root: Path, path: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def _manifest_and_spine(opf_root: ET.Element, opf_dir: str) -> tuple[dict[str, dict[str, str]], list[str], str]:
    manifest: dict[str, dict[str, str]] = {}
    for item in opf_root.findall(r".//{*}manifest/{*}item"):
        item_id = str(item.attrib.get("id") or "").strip()
        href = _safe_target(opf_dir, item.attrib.get("href"))
        if not item_id or not href:
            continue
        manifest[item_id] = {
            "href": href,
            "media_type": str(item.attrib.get("media-type") or "").strip(),
            "properties": str(item.attrib.get("properties") or "").strip(),
        }
    spine_element = opf_root.find(r".//{*}spine")
    spine = [] if spine_element is None else [
        str(item.attrib.get("idref") or "").strip()
        for item in spine_element.findall(r"./{*}itemref")
        if str(item.attrib.get("idref") or "").strip()
    ]
    toc_id = "" if spine_element is None else str(spine_element.attrib.get("toc") or "").strip()
    return manifest, spine, toc_id


def _build_target_map(root: Path, manifest: dict[str, dict[str, str]], spine: list[str]) -> dict[str, int]:
    targets: dict[str, int] = {}
    for page_index, item_id in enumerate(spine):
        item = manifest.get(item_id)
        if not item:
            continue
        page_rel = item["href"]
        targets.setdefault(page_rel, page_index)
        page_path = root / Path(page_rel)
        try:
            page = ET.parse(page_path).getroot()
        except (OSError, ET.ParseError):
            continue
        page_dir = posixpath.dirname(page_rel)
        for node in page.iter():
            if _local(node.tag) not in {"img", "image"}:
                continue
            for key, value in node.attrib.items():
                if _local(key) not in {"src", "href"}:
                    continue
                target = _safe_target(page_dir, value)
                if target:
                    targets.setdefault(target, page_index)
    return targets


def _find_nav_item(manifest: dict[str, dict[str, str]]) -> dict[str, str] | None:
    for item in manifest.values():
        if "nav" in set(item.get("properties", "").split()):
            return item
    return None


def _resolve_page_index(base_dir: str, href: str | None, targets: dict[str, int]) -> int | None:
    target = _safe_target(base_dir, href)
    return targets.get(target) if target else None


def _parse_nav_list(ol: ET.Element, nav_dir: str, targets: dict[str, int]) -> list[dict[str, object]]:
    entries: list[dict[str, object]] = []
    for li in _direct_children(ol, "li"):
        anchor = _first_direct(li, "a")
        span = _first_direct(li, "span")
        title = _text(anchor) or _text(span)
        nested = _first_direct(li, "ol")
        children = _parse_nav_list(nested, nav_dir, targets) if nested is not None else []
        page_index = _resolve_page_index(nav_dir, anchor.attrib.get("href") if anchor is not None else None, targets)
        if not title:
            title = "章节" if (page_index is not None or children) else ""
        if title and (page_index is not None or children):
            entries.append({"title": title, "page_index": page_index, "children": children})
    return entries


def _capture_nav(root: Path, nav_rel: str, targets: dict[str, int]) -> list[dict[str, object]]:
    try:
        document = ET.parse(root / Path(nav_rel)).getroot()
    except (OSError, ET.ParseError):
        return []
    toc_nav = None
    for node in document.iter():
        if _local(node.tag) != "nav":
            continue
        nav_type = " ".join(str(value or "") for key, value in node.attrib.items() if _local(key) == "type")
        if "toc" in nav_type.split():
            toc_nav = node
            break
    if toc_nav is None:
        return []
    ol = _first_direct(toc_nav, "ol")
    if ol is None:
        return []
    return _parse_nav_list(ol, posixpath.dirname(nav_rel), targets)


def _parse_ncx_points(parent: ET.Element, ncx_dir: str, targets: dict[str, int]) -> list[dict[str, object]]:
    entries: list[dict[str, object]] = []
    for point in _direct_children(parent, "navPoint"):
        label = ""
        nav_label = _first_direct(point, "navLabel")
        if nav_label is not None:
            label = _text(_first_direct(nav_label, "text")) or _text(nav_label)
        content = _first_direct(point, "content")
        page_index = _resolve_page_index(ncx_dir, content.attrib.get("src") if content is not None else None, targets)
        children = _parse_ncx_points(point, ncx_dir, targets)
        if not label:
            label = "章节" if (page_index is not None or children) else ""
        if label and (page_index is not None or children):
            entries.append({"title": label, "page_index": page_index, "children": children})
    return entries


def _capture_ncx(root: Path, ncx_rel: str, targets: dict[str, int]) -> list[dict[str, object]]:
    try:
        document = ET.parse(root / Path(ncx_rel)).getroot()
    except (OSError, ET.ParseError):
        return []
    nav_map = next((node for node in document.iter() if _local(node.tag) == "navMap"), None)
    if nav_map is None:
        return []
    return _parse_ncx_points(nav_map, posixpath.dirname(ncx_rel), targets)


def capture_original_epub_toc(extracted_root: str | os.PathLike[str], opf_path: str | os.PathLike[str]) -> dict[str, object] | None:
    """Capture the original EPUB TOC; return None so standard KCC remains the fallback."""
    root = Path(extracted_root).resolve()
    opf_file = Path(opf_path).resolve()
    try:
        opf_rel = _root_relative(root, opf_file)
        opf = ET.parse(opf_file).getroot()
    except (OSError, ValueError, ET.ParseError):
        return None
    opf_dir = posixpath.dirname(opf_rel)
    manifest, spine, toc_id = _manifest_and_spine(opf, opf_dir)
    if not spine:
        return None
    targets = _build_target_map(root, manifest, spine)
    entries: list[dict[str, object]] = []
    source = ""
    nav_item = _find_nav_item(manifest)
    if nav_item:
        entries = _capture_nav(root, nav_item["href"], targets)
        if entries:
            source = "nav"
    if not entries:
        ncx_item = manifest.get(toc_id) if toc_id else None
        if not ncx_item:
            ncx_item = next((item for item in manifest.values() if item.get("media_type") == "application/x-dtbncx+xml"), None)
        if ncx_item:
            entries = _capture_ncx(root, ncx_item["href"], targets)
            if entries:
                source = "ncx"
    if not entries:
        return None
    return {"schema": SCHEMA, "source": source, "page_count": len(spine), "entries": entries}


def _output_href(dstdir: Path, file_entry: tuple[str, str]) -> str:
    image_dir, filename = file_entry
    oebps = dstdir / "OEBPS"
    try:
        folder = Path(image_dir).resolve().relative_to(oebps.resolve()).as_posix()
    except ValueError:
        folder = os.path.relpath(image_dir, oebps).replace("\\", "/")
    parts = ["Text" if part == "Images" else part for part in folder.split("/") if part not in {"", "."}]
    stem = os.path.splitext(str(filename))[0]
    return "/".join([*parts, stem + ".xhtml"])


def _page_map(dstdir: Path, filelist: list[tuple[str, str]]) -> dict[int, str]:
    mapping: dict[int, str] = {}
    for entry in filelist:
        match = _PAGE_RE.search(str(entry[1]))
        if not match:
            continue
        page_index = int(match.group(1)) - 1
        if page_index >= 0:
            mapping.setdefault(page_index, _output_href(dstdir, entry))
    return mapping


def _remap_nodes(nodes: list[dict[str, object]], pages: dict[int, str]) -> list[dict[str, object]]:
    remapped: list[dict[str, object]] = []
    for node in nodes:
        children = _remap_nodes(list(node.get("children") or []), pages)
        raw_index = node.get("page_index")
        href = pages.get(raw_index) if isinstance(raw_index, int) else None
        title = " ".join(str(node.get("title") or "章节").split()) or "章节"
        if href is not None or children:
            remapped.append({"title": title, "href": href, "children": children})
    return remapped


def _first_href(node: dict[str, object]) -> str | None:
    href = node.get("href")
    if isinstance(href, str) and href:
        return href
    for child in list(node.get("children") or []):
        found = _first_href(child)
        if found:
            return found
    return None


def _render_nav(title: str, language: str, nodes: list[dict[str, object]], pages: dict[int, str]) -> bytes:
    ET.register_namespace("", XHTML_NS)
    ET.register_namespace("epub", EPUB_NS)
    html = ET.Element(f"{{{XHTML_NS}}}html", {f"{{{XML_NS}}}lang": language or "en-US"})
    head = ET.SubElement(html, f"{{{XHTML_NS}}}head")
    ET.SubElement(head, f"{{{XHTML_NS}}}title").text = title
    ET.SubElement(head, f"{{{XHTML_NS}}}meta", {"charset": "utf-8"})
    body = ET.SubElement(html, f"{{{XHTML_NS}}}body")
    nav = ET.SubElement(body, f"{{{XHTML_NS}}}nav", {f"{{{EPUB_NS}}}type": "toc", "id": "toc"})
    top_ol = ET.SubElement(nav, f"{{{XHTML_NS}}}ol")

    def append_nodes(parent: ET.Element, items: list[dict[str, object]]) -> None:
        for item in items:
            li = ET.SubElement(parent, f"{{{XHTML_NS}}}li")
            href = item.get("href")
            if isinstance(href, str) and href:
                link = ET.SubElement(li, f"{{{XHTML_NS}}}a", {"href": href})
                link.text = str(item.get("title") or "章节")
            else:
                ET.SubElement(li, f"{{{XHTML_NS}}}span").text = str(item.get("title") or "章节")
            children = list(item.get("children") or [])
            if children:
                nested = ET.SubElement(li, f"{{{XHTML_NS}}}ol")
                append_nodes(nested, children)

    append_nodes(top_ol, nodes)
    page_nav = ET.SubElement(body, f"{{{XHTML_NS}}}nav", {f"{{{EPUB_NS}}}type": "page-list"})
    page_ol = ET.SubElement(page_nav, f"{{{XHTML_NS}}}ol")
    for page_index, href in sorted(pages.items()):
        li = ET.SubElement(page_ol, f"{{{XHTML_NS}}}li")
        link = ET.SubElement(li, f"{{{XHTML_NS}}}a", {"href": href})
        link.text = str(page_index + 1)
    xml = ET.tostring(html, encoding="utf-8", xml_declaration=False)
    return b'<?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE html>\n' + xml + b"\n"


def _render_ncx(title: str, language: str, uid: str, nodes: list[dict[str, object]]) -> bytes:
    ET.register_namespace("", NCX_NS)
    ncx = ET.Element(f"{{{NCX_NS}}}ncx", {"version": "2005-1", f"{{{XML_NS}}}lang": language or "en-US"})
    head = ET.SubElement(ncx, f"{{{NCX_NS}}}head")
    ET.SubElement(head, f"{{{NCX_NS}}}meta", {"name": "dtb:uid", "content": f"urn:uuid:{uid}"})
    ET.SubElement(head, f"{{{NCX_NS}}}meta", {"name": "dtb:depth", "content": "1"})
    ET.SubElement(head, f"{{{NCX_NS}}}meta", {"name": "dtb:totalPageCount", "content": "0"})
    ET.SubElement(head, f"{{{NCX_NS}}}meta", {"name": "dtb:maxPageNumber", "content": "0"})
    doc_title = ET.SubElement(ncx, f"{{{NCX_NS}}}docTitle")
    ET.SubElement(doc_title, f"{{{NCX_NS}}}text").text = title
    nav_map = ET.SubElement(ncx, f"{{{NCX_NS}}}navMap")
    counter = [0]

    def append_nodes(parent: ET.Element, items: list[dict[str, object]]) -> None:
        for item in items:
            href = _first_href(item)
            if not href:
                continue
            counter[0] += 1
            point = ET.SubElement(parent, f"{{{NCX_NS}}}navPoint", {"id": f"navPoint-{counter[0]}", "playOrder": str(counter[0])})
            label = ET.SubElement(point, f"{{{NCX_NS}}}navLabel")
            ET.SubElement(label, f"{{{NCX_NS}}}text").text = str(item.get("title") or "章节")
            ET.SubElement(point, f"{{{NCX_NS}}}content", {"src": href})
            append_nodes(point, list(item.get("children") or []))

    append_nodes(nav_map, nodes)
    return ET.tostring(ncx, encoding="utf-8", xml_declaration=True) + b"\n"


def _atomic_pair(nav_path: Path, nav_bytes: bytes, ncx_path: Path, ncx_bytes: bytes) -> None:
    temps: list[Path] = []
    try:
        for target, payload in ((nav_path, nav_bytes), (ncx_path, ncx_bytes)):
            target.parent.mkdir(parents=True, exist_ok=True)
            fd, temp_name = tempfile.mkstemp(prefix=f".{target.name}.", suffix=".tmp", dir=str(target.parent))
            with os.fdopen(fd, "wb") as stream:
                stream.write(payload)
                stream.flush()
                os.fsync(stream.fileno())
            temps.append(Path(temp_name))
        os.replace(temps[0], nav_path)
        os.replace(temps[1], ncx_path)
    finally:
        for temp in temps:
            try:
                temp.unlink(missing_ok=True)
            except OSError:
                pass


def rewrite_preserved_toc(dstdir: str | os.PathLike[str], title: str, filelist: list[tuple[str, str]], model: dict[str, object] | None, language: str, uid: str) -> bool:
    """Replace KCC's flat TOC with the safely remapped original hierarchy."""
    if not model or model.get("schema") != SCHEMA:
        return False
    entries = deepcopy(list(model.get("entries") or []))
    if not entries:
        return False
    root = Path(dstdir)
    pages = _page_map(root, filelist)
    if not pages:
        return False
    nodes = _remap_nodes(entries, pages)
    if not nodes or not any(_first_href(node) for node in nodes):
        return False
    nav_bytes = _render_nav(str(title), str(language or "en-US"), nodes, pages)
    ncx_bytes = _render_ncx(str(title), str(language or "en-US"), str(uid), nodes)
    _atomic_pair(root / "OEBPS" / "nav.xhtml", nav_bytes, root / "OEBPS" / "toc.ncx", ncx_bytes)
    return True


__all__ = ["capture_original_epub_toc", "rewrite_preserved_toc", "SCHEMA"]
